library(mice)
library(naniar)
library(tidyverse)
df <- read.table("c:\\Users\\JohnM\\Documents\\MRC DTP\\Analysis_2 Local\\df_MI_09_05.tab")
MI_Df <- subset(df, select= -c(disability_10, ID, Count_Sport_High))
##Specify var class before MICE##
MI_Df$Sex.x <- factor(MI_Df$Sex.x)
MI_Df$sport_10 <- factor(
  x = MI_Df$sport_10, ordered = FALSE)
MI_Df$Sports_16 <- factor(
  x = MI_Df$Sports_16, ordered = FALSE)
class(MI_Df$Sports_16)
MI_Df$Education <- factor(
  x = MI_Df$Education,  ordered = FALSE)
MI_Df$Sportstrichotomous42 <- factor(
  x = MI_Df$Sportstrichotomous42, ordered = FALSE)
MI_Df$SportsTrichotomy46 <- factor(
  x = MI_Df$SportsTrichotomy46, ordered = FALSE)
# MI_Df$disability_10 <- ordered(
# x = MI_Df$disability_10, levels = c(0, 1, 2))
MI_Df$SEC_102 <- factor(
  x = MI_Df$SEC_102, ordered = FALSE)
MI_Df$SEC.x <- factor(
  x = MI_Df$SEC.x, ordered = FALSE)
MI_Df$Diabetes.x <- factor(MI_Df$Diabetes.x)
MI_Df$AlcRisk.x <- ordered(
  x = MI_Df$AlcRisk.x, levels = c(0, 1, 2))
MI_Df$Smoker.x <- ordered(
  x = MI_Df$Smoker.x, levels = c(0, 1, 2, 3))
MI_Df$Open_Skill_Tri16 <- factor(
  x = MI_Df$Open_Skill_Tri16, ordered = FALSE)
MI_Df$Open_Skill_Tri42 <- factor(
  x = MI_Df$Open_Skill_Tri42, ordered = FALSE)
MI_Df$Open_Skill_Tri46 <- factor(
  x = MI_Df$Open_Skill_Tri46, ordered = FALSE)
MI_Df$Closed_Skill_Tri16 <- factor(
  x = MI_Df$Closed_Skill_Tri16, ordered = FALSE)
MI_Df$Closed_Skill_Tri42 <- factor(
  x = MI_Df$Closed_Skill_Tri42, ordered = FALSE)
MI_Df$Closed_Skill_Tri46 <- factor(
  x = MI_Df$Closed_Skill_Tri46, ordered = FALSE)
MI_Df$CVDHTN <- factor(MI_Df$CVDHTN)
MI_Df$RHR <- as.numeric(MI_Df$RHR)
MI_Df$BP <- as.numeric(MI_Df$BP)
MI_Df$g5 <- as.numeric(MI_Df$g5)
MI_Df$CholHDL <- as.numeric(MI_Df$nonHDLratio)
MI_Df$Admissions <- as.numeric(MI_Df$Admissions)
MI_Df$executive_z2 <- as.numeric(MI_Df$executive_z2)
MI_Df$memory_z2 <- as.numeric(MI_Df$memory_z2)
MI_Df$composite_z2 <- as.numeric(MI_Df$composite_z2)
map(MI_Df, class)

##Examine Missingness
gg_miss_var(MI_Df)
vis_miss(MI_Df)

##MICE
Imputed_DF <- mice(data=MI_Df, m=60, maxit=5, seed=12345)

MI_Df$ID <- df$ID
MI_Df$Count_Sport_High <- factor(df$Count_Sport_High, ordered=FALSE)
temp <- subset(MI_Df, select=c(ID, SportsTrichotomy46, Sportstrichotomous42, Sports_16, sport_10, Closed_Skill_Tri46, Closed_Skill_Tri42, Closed_Skill_Tri16, Open_Skill_Tri46, Open_Skill_Tri42, Open_Skill_Tri16, Count_Sport_High))
names(temp) <- c("ID", "SportsTrichotomy46M", "Sportstrichotomous42M", "Sports_16M", "sport_10M", "Closed_Skill_Tri46M", "Closed_Skill_Tri42M", "Closed_Skill_Tri16M", "Open_Skill_Tri46M", "Open_Skill_Tri42M", "Open_Skill_Tri16M", "Count_Sport_HighM")
d2 <- complete(Imputed_DF,'long', include = T) # imputed datasets in long format (including the original)
d3 <- cbind(ID, d2)
d3 <- cbind(temp, d3) # as datasets are ordered simply cbind `id`
m2 <- as.mids(d3) # and transform back to mids object
#exploring imputed df requires following rubins rules#
#bmi_mean <- with(m2, lm(BMI.x~1))
#summary(pool(bmi_mean))
##Modelling Additive Model# Executive Function#

head(m2)
head(m2$imp$RHR$`59`)

source("C:/Users/JohnM/Documents/Epi_1/Table_Builder.R")

##--------------------Proximal Distal, Executive Function-----------------------##
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions + Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ Count_Sport_HighM + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
table_sex_adj
table_full_adj
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/proximity_tableschildhood_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/proximity_tablesadulthood_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/proximity_tableshealthbehav_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/proximity_tablesRHR_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/proximity_tablesEducation_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/proximity_tablesFull_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/proximity_tablesSex_11_05.csv")

##--------------------Proximal Distal, Memory-----------------------##
##Modelling Additive Model# Memory #
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ factor(Count_Sport_HighM, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
table_full_adj
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/proximity_tableschildhood_memory_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/proximity_tablesadulthood_memory_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/proximity_tableshealthbehav_memory_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/proximity_tablesRHR_memory_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/proximity_tablesEducation_memory_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/proximity_tablesFull_memory_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/proximity_tablesSex__memory_11_05.csv")

##--------------------Proximal Distal, Composite Cogn-----------------------##
##Modelling Additive Model# Composite #
reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ factor(Count_Sport_HighM, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ Count_Sport_HighM + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ as.factor(Count_Sport_HighM) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/proximity_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/proximity_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/proximity_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/proximity_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/proximity_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/proximity_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/proximity_tablesSex_11_composite_z2_05.csv")

##----End of proximal-distal----##

##--------------------------Age 10----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ factor(sport_10M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ as.factor(sport_10M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age10_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age10_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age10_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age10_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age10_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age10_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age10_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 10----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ factor(sport_10M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ as.factor(sport_10M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age10_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age10_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age10_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age10_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age10_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age10_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age10_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 10----------------Composite_Z--------------------##

reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ factor(sport_10M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ as.factor(sport_10M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ as.factor(sport_10M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age10_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age10_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age10_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age10_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age10_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age10_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age10_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 10-------------------##


##--------------------------Age 16----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ factor(Sports_16M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ as.factor(Sports_16M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age16_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age16_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age16_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age16_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age16_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age16_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age16_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 16----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ factor(Sports_16M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ as.factor(Sports_16M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age16_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age16_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age16_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age16_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age16_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age16_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age16_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 16----------------Composite_Z--------------------##

reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ factor(Sports_16M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ as.factor(Sports_16M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ as.factor(Sports_16M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age16_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age16_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age16_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age16_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age16_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age16_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age16_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 16-------------------##




##--------------------------Age 42----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ factor(Sportstrichotomous42M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age42_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age42_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age42_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age42_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age42_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age42_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age42_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 42----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ factor(Sportstrichotomous42M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age42_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age42_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age42_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age42_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age42_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age42_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age42_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 42----------------Composite_Z--------------------##

reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ factor(Sportstrichotomous42M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ as.factor(Sportstrichotomous42M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age42_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age42_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age42_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age42_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age42_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age42_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age42_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 42-------------------##


##--------------------------Age 46----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ factor(SportsTrichotomy46M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age46_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age46_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age46_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age46_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age46_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age46_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age46_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 46----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ factor(SportsTrichotomy46M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age46_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age46_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age46_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age46_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age46_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age46_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age46_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 46----------------Composite_Z--------------------##

reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ factor(SportsTrichotomy46M, ordered = FALSE) + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ as.factor(SportsTrichotomy46M) + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age46_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age46_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age46_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age46_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age46_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age46_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age46_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 46/PA by age-------------------##



##--------------------------Age 16/OCSE----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 16----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~  Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 16----------------Composite_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ Open_Skill_Tri16M + Closed_Skill_Tri16M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age16_OCSE_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 16-------------------##

##--------------------------Age 42----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 42----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 42----------------Composite_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri42M + Open_Skill_Tri42M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age42_OCSE_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 42-------------------##


##--------------------------Age 46----------------Executive_z--------------------##
##Sensitive Period
reg_proxdist_high_Sex <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(executive_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tableschildhood_exec_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesadulthood_exec_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tableshealthbehav_exec_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesRHR_exec_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesFull_exec_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesEducation_exec_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesSex_11_exec_z2_05.csv")
##--------------------------Age 46----------------Memory_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(memory_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tableschildhood_memory_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesadulthood_memory_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tableshealthbehav_memory_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesRHR_memory_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesFull_memory_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesEducation_memory_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesSex_11_memory_z2_05.csv")

##--------------------------Age 46----------------Composite_Z--------------------##
reg_proxdist_high_Sex <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x))
reg_proxdist_high_childhood <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions))
reg_proxdist_high_adulthealth <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions + nonHDLratio + BMI.x + B10HBA1C + BP))
reg_proxdist_high_adulthealthbehaviour <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions+ Smoker.x + AlcRisk.x))
reg_proxdist_high_RHR <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions + RHR))
reg_proxdist_high_education <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + g5 + SEC_102 + Admissions  + Education))
reg_proxdist_high_full <- with(m2, lm(composite_z2 ~ Closed_Skill_Tri46M + Open_Skill_Tri46M + Sex.x + Smoker.x + AlcRisk.x + nonHDLratio + B10HBA1C + g5 + SEC_102 + Admissions + BP + BMI.x + RHR + Education))
table_sex_adj <-  Mice_output(reg_proxdist_high_Sex)
table_childhood_adj <-  Mice_output(reg_proxdist_high_childhood)
table_adulthood_adj <-  Mice_output(reg_proxdist_high_adulthealth)
table_education_adj <-  Mice_output(reg_proxdist_high_education)
table_healthbehav_adj <-  Mice_output(reg_proxdist_high_adulthealthbehaviour)
table_RHR_adj <-  Mice_output(reg_proxdist_high_RHR)
table_full_adj <-  Mice_output(reg_proxdist_high_full)
write.csv(table_childhood_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tableschildhood_composite_z2_11_05.csv")
write.csv(table_adulthood_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesadulthood_composite_z2_11_05.csv")
write.csv(table_healthbehav_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tableshealthbehav_composite_z2_11_05.csv")
write.csv(table_RHR_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesRHR_composite_z2_11_05.csv")
write.csv(table_full_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesFull_composite_z2_11_05.csv")
write.csv(table_education_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesEducation_composite_z2_11_05.csv")
write.csv(table_sex_adj, "C:/Users/JohnM/Downloads/age46_OCSE_tablesSex_11_composite_z2_05.csv")

##--------------------End of Age 46-------------------##




##chop/change OSCE
##remove games

